version: '3'
services:
  postgresql:
    image: postgres:10.5
    container_name: db-sugiyama
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root

  app:
    container_name: app
    ports:
      - 8080:8080
    # postgres をビルドした後に app をビルド
    depends_on:
      - postgresql
    # Dockerfile を指定
    build:
      context: .
    # GOPATHを指定
    environment:
      - GOPATH=/go
    # フォルダ共有（ホストOS:コンテナ）
    volumes:
      - ./go:/go/src/app/go/
    # docker-compose run 実行時に実行されるコマンド
    command: go run main.go
