version: '3'
services:
  postgresql:
    image: postgres:10.5
    container_name: db-sugiyama
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root

  app:
    container_name: app
    depends_on: 
      - postgresql
    build: .
    ports:
      - $PORT:$PORT
    environment:
      PORT: $PORT
